#!/usr/bin/env bash

# $1 the command
# .desktop location
desktop_location="$HOME/.local/share/applications"
command=$1

echo "This is what is going to be created:"
create_file="touch $desktop_location/$command.desktop"
header="echo [Desktop Entry] > $desktop_location/$command.desktop"
type="echo Type=Application >> $desktop_location/$command.desktop"
name="echo Name=$command >> $desktop_location/$command.desktop"
term="echo Terminal=false >> $desktop_location/$command.desktop"
exec="echo Exec=$(pwd)/$command >> $desktop_location/$command.desktop"
# Create file
echo $create_file
echo $header
echo $type
echo $name
echo $term
echo $exec
read -rep "Are you sure? (y/n)" ans

if [ -f "$desktop_location/$command.desktop" ]; then
    echo "That file already exists"
    exit 1
fi

if [[ "$ans" == "y" || "$ans" == Y ]]; then
    echo "ok"
    touch $desktop_location/$command.desktop
    echo [Desktop Entry] > $desktop_location/$command.desktop
    echo Type=Application >> $desktop_location/$command.desktop
    echo Name=$command >> $desktop_location/$command.desktop
    echo Terminal=false >> $desktop_location/$command.desktop
    echo Exec=$(pwd)/$command >> $desktop_location/$command.desktop
else
    exit 0
fi
