#!/usr/bin/env bash

# get remote branches
branches=$({
    git branch -r
    echo "[Cancel]"
} | sed 's/^[[:space:]]*//' | sed 's/origin\///' | fzf)

if [[ -z $branches || $branches == "[Cancel]" ]]; then
    exit 0
fi

gh pr create --fill --base "$branches" 2>&1

gh pr view --web
